version: "3"

services:
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env.docker
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - ./.env.db
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: