"""leftovers

Revision ID: a6ab7f52e1e5
Revises: 5982c3776d5f
Create Date: 2022-04-25 14:18:53.861395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ab7f52e1e5'
down_revision = '5982c3776d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
